version: 2
endpoint: http://localhost:5000
admin_secret: a_long_secret_that_should_never_be_used_in_production
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
