version: '3.6'
services:
  postgres:
    ports:
      - '5432:5432'
  graphql-engine:
    ports:
      - '8080:8080'
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
  hasura-backend-plus:
    env_file: '.env.development'
    depends_on:
      - 'mailhog'
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_SECURE: 'false'
  minio:
    ports:
      - 8000:9000 # Do not use port 9000 in the host machine as developpers using portainer might already use it
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
