version: '3.6'
services:
  graphql-engine:
    ports:
      - '8080'
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
  hasura-backend-plus:
    env_file: '.env.production'
  frontend:
    build: ../client

networks:
  default:
    external:
      name: nginxproxymanager_default
